"""
Django settings for preprddeploy project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
import djcelery

djcelery.setup_loader()
BROKER_URL = 'redis://localhost:6379/0'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!n3ft=ayi8d(tkqav*9=zqa)$3thn6nn*un=vg*2(p!*tb&a3c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ADMINS = (
   ('dengken', 'dengken@tp-link.com.cn'),
)
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'guardian',
    'django_ses',
    'djcelery',
    'common',
    'permission',
    'module',
    'elb',
    'basicservice',
    'bizmodule'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # this is default
    'guardian.backends.ObjectPermissionBackend',
)

ROOT_URLCONF = 'preprddeploy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'preprddeploy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'preprddeploy',
        'HOST': '127.0.0.1',
        'USER': 'root',
        'PASSWORD': 'root'
    }
}

LOGIN_URL = '/user/login'
LOGIN_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = False

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, "static")

STATIC_URL = '/static/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'common': {
            'format': '%(asctime)s|%(levelname)s|%(threadName)s|%(filename)s:%(lineno)d| - %(message)s'
        }
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'common'
        },
        'common': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/common.log'),
            'when': 'D',
            'interval': 1,
            'backupCount': 7,
            'formatter': 'common',
            'filters': ['require_debug_false']
        },
        'autodeploy_log': {
            'level': 'DEBUG',
            'filters': ['require_debug_false'],
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/autodeploy.log'),
            'formatter': 'common'
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'propagate': True,
            'level': 'INFO',
        },
        'common': {
            'handlers': ['common', 'console'],
            'propagate': False,
            'level': 'DEBUG'
        },
        'deploy': {
            'handlers': ['common', 'console', 'autodeploy_log'],
            'propagete': False,
            'level': 'DEBUG'
        }
    }
}

PREPRD_VPC = {
    "cn-north-1": ['vpc-prd', 'vpc-8d92d2e8']
}

ELB_MODULES = {
        'connector': ['preprd-elb-connector-0'],
        'appserverinternal': ['preprd-internal-elb-appserver-0'],
        'account_accountweb': ['preprd-elb-accountweb-0'],  # for en
        'appserver': ['preprd-elb-appserver-0'],
        'mail': ['preprd-internal-elb-mail-0'],  # for en: sms?
        'vaserver': ['preprd-elb-vaserver-0', 'preprd-internal-elb-vaserver-0'],  # for en
        'sefcore': ['preprd-elb-sefcore-0'],
        'appconnector': ['preprd-elb-appconnector-0'],
        'devconnector': ['preprd-elb-devconnector-0'],
        'eweb': ['preprd-elb-eweb-0'],  # for en
        'dal': ['preprd-elb-dal-0'],
        'dalForFailover': ['preprd-elb-hacache-0']
}

TOPO_MODULES = ['nat', 'ci_test', 'dns']

ACCOUNT_NAME = 'beta'
HOME_PATH = '/home/ubuntu'
STATIC_DIR = os.path.join(BASE_DIR, 'static')
HOSTS_CACHE_TIME_SECONDS = 60
